telegram:
  bot_token: null
  chat_id: null

code_agents:
  gemini:
    command: /usr/bin/gemini
    models:
      - gemini-3.1-flash-lite
    new_args:
      - "--model"
      - "{model}"
      - "--skip-trust"
      - "--approval-mode"
      - yolo
      - "--output-format"
      - json
      - "--prompt"
      - "{prompt}"
    resume_args:
      - "--model"
      - "{model}"
      - "--skip-trust"
      - "--approval-mode"
      - yolo
      - "--resume"
      - "{sessionId}"
      - "--output-format"
      - json
      - "--prompt"
      - "{prompt}"
    stream_args:
      - "--model"
      - "{model}"
      - "--skip-trust"
      - "--approval-mode"
      - yolo
      - "--output-format"
      - stream-json

  codex:
    command: /usr/bin/codex
    models:
      - gpt-5.3-codex-spark
      - gpt-5.5
    new_args:
      - exec
      - "--json"
      - "--color"
      - never
      - "--sandbox"
      - danger-full-access
      - "-m"
      - "{model}"
      - "-c"
      - service_tier="fast"
      - "--skip-git-repo-check"
      - "-"
      - stdin
    resume_args:
      - exec
      - resume
      - "--json"
      - "{sessionId}"
      - "-c"
      - sandbox_mode="danger-full-access"
      - "-m"
      - "{model}"
      - "-c"
      - service_tier="fast"
      - "--skip-git-repo-check"
      - "-"
      - stdin
    stream_args:
      - app-server
      - "-c"
      - model="{model}"
      - "-c"
      - sandbox_mode="danger-full-access"
      - "--listen"
      - "stdio://"
