telegram:
  bot_token: null
  chat_id: null

code_agents:
  gemini:
    command: agy
    models:
      - gemini-3.7-flash-low
    new_args:
      - "--new-project"
      - "--model"
      - "{model}"
      - "--dangerously-skip-permissions"
      - "--output-format"
      - json
      - "--print={prompt}"
    resume_args:
      - "--model"
      - "{model}"
      - "--dangerously-skip-permissions"
      - "--conversation"
      - "{sessionId}"
      - "--output-format"
      - json
      - "--print={prompt}"
    stream_args:
      - "--new-project"
      - "--model"
      - "{model}"
      - "--dangerously-skip-permissions"
      - "--input-format"
      - stream-json
      - "--output-format"
      - stream-json
      - "{stdin}"

  codex:
    command: /usr/bin/codex
    models:
      - gpt-5.3-codex-spark
      - gpt-5.5
    new_args:
      - exec
      - "--json"
      - "--color"
      - never
      - "--sandbox"
      - danger-full-access
      - "-m"
      - "{model}"
      - "-c"
      - "--skip-git-repo-check"
      - "{prompt}"
    resume_args:
      - exec
      - resume
      - "--json"
      - "-m"
      - "{model}"
      - "-c"
      - sandbox_mode="danger-full-access"
      - "-c"
      - "--skip-git-repo-check"
      - "{sessionId}"
      - "{prompt}"
    stream_args:
      - app-server
      - "-c"
      - model="{model}"
      - "-c"
      - sandbox_mode="danger-full-access"
      - "--listen"
      - "stdio://"
      - "{stdin}"
